### ISSUE TITLE
Demo of editing form

### ISSUE THREAD

**Issue by neitanod** [maxkostinevich/jquery-multifield#1]
It would be nice if the demo included an example of a preloaded form to use for edition (not only creation) of records.

**Comment by maxkostinevich** [comment]
Hey @neitanod thanks for your suggestion.

There is a number of ways to preload and edit existing data, for example: you can do it via AJAX, or if you use PHP - you can use foreach() loop (see the source code of example #6).

Please keep in mind: I have developed this library in ~2013 for my own needs and I do not have any plans to maintain this library. So I'd recommend you to use one of modern js-libraries and/or frameworks (e.g. React, Ember, Angular) to work with dynamic data
